### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [AOEpeople/searchperience-google-tag-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1. The company website [url](https://www.searchperience.me/) mentioned in the manifest file shows error in the certificate "ERR_CERT_COMMON_NAME_INVALID".
2. In template.tpl file please let us know the reason for using hard code value "3sixty" in line 168. Also let us know if the data is configurable?

**Comment by MarioAer** [comment]
Hello @praveena-pappu , 

Thx for checking this out. We did some changes based on your feedback.
